project:
  type: website
  pre-render: build.R
  render: 
    - test*.qmd
    - index.qmd
    - "!test_package_template.qmd"
  execute-dir: project

execute:
  freeze: auto  # re-render only when source changes
  cache: true
  
website:
  title: "Rocker UAT"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
date: now
date-format: "DD-MMM-YYYY HH:mm:ss"


