---
title: "Test Bespoke Packages"
listing:
  contents:
    - "packages/*.qmd"
  type: table
  fields: 
    - title
    - date
---

# Details

For all the non-default add-on packages we want to run the tests and example files, but not vignettes. The vignettes are meant as long-form help documentation, and can require further add-on packages that we do not want to install, hence they are not included. 


The packages that come from CRAN (or rather the Posit Archive to fix the date of the packages), the Rocker image has not included the test files. This is to save storage space for files that are not going to be used regularly.  So we have to download a copy of the source package, again from the Posit archive, with the relevant test files.  This is within the `..\packages\` directory.   We have to write a slightly modified form of the `tools::testInstalledPackage()` to tell the code where to find the test directory, in this non-standard location. 

In contrast, for the `cctu` package this is built in-house, and is included within the Rocker image by pulling from github, including the test files and comparison outputs. It required separate lines of code in a shell script to add this package, which was easy to modify so as to include test files.


# Links to Individual Package Tests
