project:
  type: website
  pre-render: build.R
  render: 
    - test*.qmd
    - page*.qmd
    - index.qmd
    - "!template.qmd"
  
website:
  title: "web_local"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


