name: Build landing page
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: shug0131/cctu:latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
#      - name: run build
#        run: Rscript -e 'source("generate_versions.R")'

      - name: Build site
        run: |
          quarto render --profile github-landing

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site