name: Build and Deploy
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: shug0131/cctu:4.4.0
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: run build
        run: Rscript -e 'source("build.R")'

      - name: Build site
        run: |
          quarto render --profile github

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs