name: Update versions from docker hub

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: shug0131/cctu:latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set as safe for following git commands
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Make changes to pull request
        run: |
          Rscript generate-versions.R
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Automatic update of image versions info files
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          branch: auto-detected-update
          delete-branch: true
          title: 'Automatic update of image version info files'
          body: |
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"